services:
  bot:
    image: "botalovserg/app-bot-docker"
    # build:
    #   context: .
    # environment:
    #   - APP_DB_URL=postgresql+asyncpg://botalov:botalov@db/bot_db
    restart: "unless-stopped"
    volumes:
      - "/home/botalov/mycode/telegram-bot-notes/.env:/app/.env"
    networks:
      - my_networks
    command: ./run.sh

    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:latest
    env_file:
      - .env.docker
    ports:
      - "5435:5432"
    networks:
      - my_networks
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


networks:
  my_networks:
    name: my_networks